server:
  port: 8008

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/mycourse?createDatabaseIfNotExist=true
    username: root
    password: password
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        hbm2ddl:
          auto: update
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    show-sql: true
  liquibase:
    change-log: classpath:liquibase/changelog-master.yml
    enabled: false
